# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3febace25e77f8b1a0ffceaedfa1a7b75787e23f52b2cd57382019c6a58eaeb5770dc20bf4d39fa08cbadc03da6ea238e8fc477fd1a4690e3d6bc31193ce226d

test:
  secret_key_base: 06d13936da9dde827375d6fe21ff52253b5ef6ecc1138cc442b8ed7caf4a43f6960211b198aeb61ee6ed7587f94c6a4da7120c3e3f27f2b59cb94386b910d70f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
